package Pojos;
// Generated 2/11/2016 10:27:29 AM by Hibernate Tools 4.3.1



/**
 * Materiales generated by hbm2java
 */
public class Materiales  implements java.io.Serializable {


     private Integer idmateriales;
     private String nombre;
     private Integer preciocost;
     private Integer cantidad;

    public Materiales() {
    }

    public Materiales(String nombre, Integer preciocost, Integer cantidad) {
       this.nombre = nombre;
       this.preciocost = preciocost;
       this.cantidad = cantidad;
    }
   
    public Integer getIdmateriales() {
        return this.idmateriales;
    }
    
    public void setIdmateriales(Integer idmateriales) {
        this.idmateriales = idmateriales;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPreciocost() {
        return this.preciocost;
    }
    
    public void setPreciocost(Integer preciocost) {
        this.preciocost = preciocost;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


