package Pojos;
// Generated 2/11/2016 10:27:29 AM by Hibernate Tools 4.3.1



/**
 * Puertas generated by hbm2java
 */
public class Puertas  implements java.io.Serializable {


     private Integer idpuertas;
     private String nombre;
     private Integer preciocot;
     private Integer cantidad;

    public Puertas() {
    }

	
    public Puertas(String nombre) {
        this.nombre = nombre;
    }
    public Puertas(String nombre, Integer preciocot, Integer cantidad) {
       this.nombre = nombre;
       this.preciocot = preciocot;
       this.cantidad = cantidad;
    }
   
    public Integer getIdpuertas() {
        return this.idpuertas;
    }
    
    public void setIdpuertas(Integer idpuertas) {
        this.idpuertas = idpuertas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPreciocot() {
        return this.preciocot;
    }
    
    public void setPreciocot(Integer preciocot) {
        this.preciocot = preciocot;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


