package Pojos;
// Generated 2/11/2016 10:27:29 AM by Hibernate Tools 4.3.1



/**
 * Vitrinas generated by hbm2java
 */
public class Vitrinas  implements java.io.Serializable {


     private Integer idvitrinas;
     private String nombre;
     private Integer preciocot;
     private Integer cantidad;

    public Vitrinas() {
    }

	
    public Vitrinas(String nombre) {
        this.nombre = nombre;
    }
    public Vitrinas(String nombre, Integer preciocot, Integer cantidad) {
       this.nombre = nombre;
       this.preciocot = preciocot;
       this.cantidad = cantidad;
    }
   
    public Integer getIdvitrinas() {
        return this.idvitrinas;
    }
    
    public void setIdvitrinas(Integer idvitrinas) {
        this.idvitrinas = idvitrinas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPreciocot() {
        return this.preciocot;
    }
    
    public void setPreciocot(Integer preciocot) {
        this.preciocot = preciocot;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


